version: '3.9'

services:

  mysql:
    image: docker.io/library/mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: calcr
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data/changesets:/docker-entrypoint-initdb.d

  influxdb:
    image: docker.io/library/influxdb:2.0
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: andreasherold
      DOCKER_INFLUXDB_INIT_BUCKET: calcr_metrics
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 49fff1905acab043e75bae4d3350352c8f7e400e98c4b9f99698788c4a2146ba

volumes:
  mysql-data:
  influxdb-data: